# Generated by Django 5.0.4 on 2024-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(default=1)),
                ('plan_name', models.CharField(max_length=255)),
                ('project_create', models.IntegerField(default=1)),
                ('add_files', models.IntegerField(default=2)),
                ('file_size', models.IntegerField(default=5)),
                ('multifields', models.CharField(default='bar', max_length=255)),
                ('chart_plots', models.CharField(default='B,L,P', max_length=255)),
                ('color_selection', models.BooleanField(default=0)),
                ('custom_theme', models.BooleanField(default=0)),
                ('graph_limit', models.IntegerField(default=3)),
                ('logs', models.BooleanField(default=0)),
                ('chart_download', models.CharField(default='J, J-PD-PN, A', max_length=255)),
                ('shares', models.IntegerField(default=1)),
                ('pdf_download', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('plan', models.IntegerField(default=1)),
                ('project_create', models.IntegerField(default=1)),
                ('add_files', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=5)),
                ('multifields', models.CharField(default='bar', max_length=255)),
                ('chart_plots', models.CharField(default='B, L, P', max_length=255)),
                ('graph_limit', models.IntegerField(default=0)),
                ('chart_download', models.CharField(default='J, J-PD-PN, A', max_length=255)),
                ('shares', models.IntegerField(default=0)),
            ],
        ),
    ]
