# Generated by Django 3.2 on 2024-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project_create',
            field=models.IntegerField(default=0),
        ),
    ]
