# Generated by Django 5.0.6 on 2024-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_project_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
