# Generated by Django 5.0.6 on 2024-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_card_user_alter_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
