# Generated by Django 5.0.6 on 2024-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='account_create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='add_files',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='file_size',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='graph_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='plan_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='project_create',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='shares',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
