# Generated by Django 5.0.6 on 2024-06-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_trash_account_create_date_trash_add_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='account_create_date',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='plan_exp_date',
        ),
    ]
